# Deep Learning with PyTorch: A 60 Minute Blitz

## Getting Started
### Tensors

In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[5.8270e-10, 8.2990e-33, 1.3563e-19],
        [1.3563e-19, 1.3563e-19, 2.4754e-12],
        [2.4756e-12, 7.8447e+17, 1.3556e-19],
        [1.3563e-19, 1.3563e-19, 7.9717e-10],
        [5.8270e-10, 5.9669e-07, 8.2990e-33]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6962, 0.8085, 0.7484],
        [0.5038, 0.2450, 0.4797],
        [0.0936, 0.8009, 0.8215],
        [0.8988, 0.2747, 0.8967],
        [0.0688, 0.6172, 0.0565]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = torch.tensor([[1.1, 2], [3.3, 4], [5.5, 6]])
print(x)

tensor([[1.1000, 2.0000],
        [3.3000, 4.0000],
        [5.5000, 6.0000]])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6785,  1.0051, -0.7075],
        [ 1.0809, -0.0587,  0.5851],
        [-0.5518, -0.4100, -1.0192],
        [ 1.0273, -0.2768,  0.5421],
        [-0.2891,  0.8263, -1.0179]])


In [8]:
print(x.size())

torch.Size([5, 3])


### Operations

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.5045,  1.6414,  0.1813],
        [ 1.7731,  0.6246,  0.6861],
        [ 0.1268,  0.4631, -0.6779],
        [ 1.3187,  0.5386,  0.8812],
        [ 0.5848,  0.9008, -0.6722]])


In [10]:
print(torch.add(x, y))

tensor([[-1.5045,  1.6414,  0.1813],
        [ 1.7731,  0.6246,  0.6861],
        [ 0.1268,  0.4631, -0.6779],
        [ 1.3187,  0.5386,  0.8812],
        [ 0.5848,  0.9008, -0.6722]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.5045,  1.6414,  0.1813],
        [ 1.7731,  0.6246,  0.6861],
        [ 0.1268,  0.4631, -0.6779],
        [ 1.3187,  0.5386,  0.8812],
        [ 0.5848,  0.9008, -0.6722]])


In [12]:
# add x to y
y.add_(x)
print(y)

tensor([[-1.5045,  1.6414,  0.1813],
        [ 1.7731,  0.6246,  0.6861],
        [ 0.1268,  0.4631, -0.6779],
        [ 1.3187,  0.5386,  0.8812],
        [ 0.5848,  0.9008, -0.6722]])


In [13]:
print(x)
print(x[:, 1])

tensor([[-1.6785,  1.0051, -0.7075],
        [ 1.0809, -0.0587,  0.5851],
        [-0.5518, -0.4100, -1.0192],
        [ 1.0273, -0.2768,  0.5421],
        [-0.2891,  0.8263, -1.0179]])
tensor([ 1.0051, -0.0587, -0.4100, -0.2768,  0.8263])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
m = x.view(-1, 16)
n = x.view(-1)
p = x.view(8, -1)
print(x.size(), y.size(), z.size(), m.size(), n.size(), p.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([1, 16]) torch.Size([16]) torch.Size([8, 2])


In [15]:
x = torch.rand(1)
print(x)
print(x.size())
print(x.item())
y = torch.randn(1, 1)
print(y)
print(y.size())
print(y.item())

tensor([0.1268])
torch.Size([1])
0.12676358222961426
tensor([[-0.1737]])
torch.Size([1, 1])
-0.1737450212240219


In [16]:
print(m.item())

ValueError: only one element tensors can be converted to Python scalars

### Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

In [19]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
torch.cuda.is_available()

False

## AUTOGRAD: AUTOMATIC DIFFERENTIATION

In [21]:
import torch

In [22]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [23]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [24]:
print(y.grad_fn)

In [25]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [26]:
with torch.no_grad():
    print(x, y, z, out, sep='\n')

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [27]:
a = torch.randn(2 * 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_()
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
a.requires_grad_(False)
print(a.requires_grad)
print(b.grad_fn)

False
True
False


In [28]:
print(out)
out.backward() # out.backward(torch.tensor(1.))

tensor(27., grad_fn=<MeanBackward0>)


In [29]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
print(y.grad)

None


In [31]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([0.0272, 0.6528, 2.0101], requires_grad=True)


In [32]:
y = x * 2
while y.data.norm() < 1000:
    y *= 2
print(y)

tensor([  13.9339,  334.2232, 1029.1841], grad_fn=<MulBackward0>)


In [34]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [35]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [36]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [37]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [39]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), 2)
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [40]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [41]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0461, -0.0511, -0.0715, -0.0748,  0.0404, -0.0693,  0.0085, -0.0210,
         -0.1026,  0.1203]], grad_fn=<AddmmBackward>)


In [42]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [43]:
output = net(input)
target = torch.randn(10)
print(target.size())
target = target.view(1, -1)
print(target.size())
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

torch.Size([10])
torch.Size([1, 10])
tensor(2.2036, grad_fn=<MseLossBackward>)


In [44]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [45]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([ 0.0033, -0.0205, -0.0295,  0.0114, -0.0062,  0.0153])


In [46]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [48]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)
optimizer.zero_grad()
loss = criterion(output, target)
loss.backward()
optimizer.step()

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.